## Знакомство с библиотеками для анализа данных. NumPy

Результат лабораторной работы − отчет в формате ноутбука Jupyter (ipynb-файл). Постарайтесь сделать ваш отчет интересным рассказом, последовательно отвечающим на вопросы из заданий. Помимо ответов на вопросы, в отчете так же должен быть код, однако чем меньше кода, тем лучше всем: нам − меньше проверять, вам —  проще найти ошибку или дополнить эксперимент. При проверке оценивается четкость ответов на вопросы, аккуратность отчета и кода.

### О задании

Лабораторные работы "NumPy" и "Pandas" направлены на работу с пакетами NumPy, Pandas и Matplotlib путём решения набора задач (да, алгебры и геометрии тут почти нет). В данных заданиях разрешено пользоваться только стандартной библиотекой языка Python, а также пакетами NumPy, Pandas и Matplotlib. Целью заданий является редактирование данного jupyter notebook-a (в части блоков с кодом на python) таким образом, чтобы были реализованы указанные в заданиях функции.


### Оценивание и штрафы

* Каждая из задач имеет определенную «стоимость» (указана в скобках около задачи)
* «Похожие» решения считаются плагиатом и все задействованные студенты (в том числе те, у кого списали) не могут получить за него больше 0 баллов
* Если вы нашли решение какого-то из заданий в открытом источнике, необходимо добавить ссылку на этот источник (скорее всего вы будете не единственным, кто это нашел, поэтому чтобы исключить подозрение в плагиате, необходима ссылка на источник)
* Не оцениваются задания с удалёнными формулировками
* Не оценивается лабораторная работа целиком, если она была выложена в открытый источник

###  Правила сдачи

Работу необходимо сдавать, загрузив в свой приватный репозиторий и сообщив об этом в телеграм @xrzvs (или просто открыв доступ к ноутбуку в Google Colab; более подробную информацию смотрите в README.md). 

### Знакомство с Numpy

Во всех заданиях данного ноутбука **запрещено** использовать циклы (ключевые слова *for* и *while*), [list comprehension](https://habrahabr.ru/post/30232/), [map и т.п.](http://pythonicway.com/python-functinal-programming)

Для каждой задачи приведите примеры использования реализованных функций. Без примеров баллы за задание будут снижены в 2 раза, примеры должны отличаться от тех что приведены в самом задании

Под матрицей в заданиях понимается двумерный [numpy.array](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html)

In [2]:
import numpy as np

**(0.25 балла) Задание 1.** Реализуйте функцию, принимающую на вход матрицу ```X``` и два массива индексов ```indices1``` и ```indices2``` одинаковой длины и возвращающую np.array, состоящий из последовательности элементов 

```[X[indices1[0], indices2[0]], ... , X[indices1[N-1], indices2[N-1]]]```

In [5]:
a1 = np.array([1, 3, 5])
a2 = np.array([2, 4, 6])
x = np.arange(49).reshape(7, 7)


def construct_array(X, indices1, indices2):
    return X[indices1, indices2]



assert np.allclose (construct_array(np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]]), [1, 2, 3], [2, 1, 0]), np.array([6,8, 10]))
construct_array(x, a1, a2)
# Level1: всё просто (хотя для многих это неочевидно, они пытаются искать сложности там, где их нет)

array([ 9, 25, 41])

**(0.25 балла) Задача 2.** Реализуйте функцию, которая на вход принимает два массива ```X``` и ```Y``` (массивы могут быть n-мерные, но их размерности должны совпадать), а возвращает **True** если они равны и **False** - иначе.

In [6]:
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a3 = np.array([[[1, 2],
                [3, 4], 
                [5, 6], 
                [7, 8], 
                [9, 10], 
                [11, 12], 
                [13, 14], 
                [15, 16]]])
a4 = np.array([[[1, 2],
                [3, 4], 
                [5, 6], 
                [7, 8], 
                [9, 10], 
                [11, 12], 
                [13, 14],
                [14, 15]]])

def detect_identic(X, Y):
    return not np.any((X != Y))
assert np.allclose (detect_identic(np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]]), np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 11]])), False)
assert np.allclose (detect_identic(np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]]), np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])), True)
detect_identic(a3, a4)

# Level 2: Отрицание от логического "Или"

False

**(0.25 балла) Задание 3.** Реализуйте функцию, которая на вход принимает цветное изображение ```X``` (трехмерный вектор размера (n, m, 3)) и возвращает среднее значение по трём каналам (вектор длины 3).

In [21]:
a = np.arange(60).reshape(2, 10, 3)


def mean_channel(X):
    return np.mean(X, axis=1)[1]


assert np.allclose(mean_channel(np.arange(27).reshape((3, 3, 3))), np.array([12., 13., 14.]))

mean_channel(a)

# Level 3: Просто транспонируем и считаем средние

array([43.5, 44.5, 45.5])

**(0.25 балла) Задание 4. ** Реализуйте функцию, принимающую на вход матрицу ```X``` и некоторое число ```a``` и возвращающую ближайший к числу элемент матрицы.

Например, для ```X = np.arange(0,10).reshape((2, 5))``` и ```a = 3.6``` ответом будет 4.

In [24]:
a = np.array([[1,  2,  3.2,  4],
              [5,  6,  7,  8], 
              [9, 10, 11, 12], 
              [13, 14, 15, 16]])
value = 2.9
def nearest_value(X, a):
    return X[np.unravel_index(np.abs(X-a).argmin(), X.shape)]

''' Level 4: Берем значение по индексу:
             unravel index от минимального элемента из матрицы разностей
'''

assert np.allclose (nearest_value(np.arange(0,1000).reshape((10, 10, 10)), -1), 0)
assert np.allclose (nearest_value(np.arange(0,1000).reshape((10, 10, 10)), 160.5), 160)
assert np.allclose (nearest_value(np.arange(0,1000).reshape((10, 10, 10)), 160.6), 161)
nearest_value(a, value)


3.2

**(0.5 балла) Задача 5.** Реализуйте функцию, принимающую на вход два одномерных массива ```x``` и ```y``` и возвращающую матрицу, в которой первый массив соответствует первому столбцу матрицы, второй - второму.

В этом задании **запрещается** пользоваться операцией транспонирования и рекомедуется воспользоваться методом [reshape](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.reshape.html).

In [100]:
a1 = np.array([1, 2, 3, 4])
a2 = np.array([2, 4, 6, 8])
def construct_matrix(x, y):
    return np.append(x.reshape(len(x), 1), y.reshape(len(y), 1), axis=1)
assert np.allclose (construct_matrix(np.arange(0, 6), np.arange(6, 12)), np.array([[0, 6], [1, 7], [2, 8], [3, 9], [4, 10], [5, 11]]))
construct_matrix(a1, a2)
# Level 5: Аналог транспонирования через изменение формы
# В задании не сказано, что делать, если массивы различной длины, поэтому считаем, что такой ситуации не будет


array([[1, 2],
       [2, 4],
       [3, 6],
       [4, 8]])

**(0.5 балла) Задание 6.** Реализуйте функцию, которая на вход принимает вектор ```x```, содержащий целые числа, кроме 0, а возвращает вектор со вставленными нулями между числами.

Например, из ```[1, -5, 3]``` получить ```[1, 0, -5, 0, 3]```

In [98]:
a1 = np.array([1, 2, 3, 4])
def add_zeros(x):
    return np.append(x.reshape(len(x), 1), np.zeros(len(x)).reshape(len(x), 1), axis=1) \
            .reshape(len(x)*2)[:-1]
add_zeros(a1)
# Level 6: По сути аналогично предыдущему заданию, только вставляем 0 и меняем форму обратно, убираем последний 0
assert np.allclose (add_zeros(np.arange(1, 10)), np.array([1., 0., 2., 0., 3., 0., 4., 0., 5., 0., 6., 0., 7., 0., 8., 0., 9.]))
assert np.allclose (add_zeros(np.array([1])), np.array([1]))
assert np.allclose (add_zeros(np.array([])), np.array([]))
add_zeros(np.arange(1, 10))

array([1., 0., 2., 0., 3., 0., 4., 0., 5., 0., 6., 0., 7., 0., 8., 0., 9.])

**(0.75 балла) Задание 7.** Реализуйте функцию для подсчёта произведения ненулевых элементов на диагонали прямоугольной матрицы

Например, для ```X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])``` ответом является 3. Если ненулевых элементов нет, функция должна возвращать ```None```.

In [93]:
def nonzero_product(X):
    return X.diagonal()[X.diagonal().nonzero()].prod() \
            if len(X.diagonal()[X.diagonal().nonzero()]) else None
a = np.array([[0, 0, 1, 2],
              [2, 1, 2, 7], 
              [3, 0, 0, 9], 
              [4, 5, 6, 0]])
# print(nonzero_product(a))
#Level 7: Произведение элементов по индексам [мн-во миндексов диагональных элементов, 
#                                                                          не равных 0] 
assert np.allclose (nonzero_product(np.array([[3, 3, 3], [5, 5, 5], [7, 7, 0]])), 15)
assert nonzero_product(np.array([[0, 3, 3], [5, 0, 5], [7, 7, 0]])) == None


**(0.75 балла) Задание 8.** Реализуйте функцию, возвращающую максимальный элемент в массиве ```X``` среди элементов, перед которыми стоит нулевой.

Например, для ```X = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])``` ответом является 5. Если подходящих элементов нет, функция должна возвращать ```None```.

In [88]:
a = np.array([[100, 0, 1, 2],
              [2, 1, 2, 7], 
              [3, 0, 0, 9], 
              [4, 5, 6, 0]]).reshape(16)
b = np.array([1, 2, 3, 5, 1, 4, 2, 9, 1, 5, 11, 0])
def max_element(X):
    if sum(np.shape(np.where(X == 0))) == 1:
        return None
    a = np.append(X, 0)[np.where(X == 0)[0]+1]
    return a[a.nonzero()].max() if np.any(a) else None
          
print(max_element(a), max_element(b))
#Level 8: Ищем индексы нулевых элементов и прибавляем к ним 1, потом ищем среди этих
#              элементов максимальный
# В начале дописываем в конец минимальный элемент массива, чтобы не выходить за границы массива,
#              когда последний элемент - 0
assert max_element(np.array([1,2,3,4,5])) == None
assert max_element(np.array([1,0,0,0,0])) == None
assert np.allclose(max_element(np.array([1,0,3,2,0])), 3)


9 None


**(0.75 балла) Задание 9.** Реализуйте функцию, принимающую на вход матрицу ```X``` и возвращающую все её уникальные строки в виде матрицы.

In [47]:
a = np.array([[1, 2, 3],
            [4, 5, 6],
            [1, 2, 3]])
def get_unique_rows(X):
    return np.unique(X, axis=0)
get_unique_rows(a)
# Level 9: Просто unique
assert np.allclose (get_unique_rows(np.array([[1, 2], [1, 9], [1, 2],[1, 9]])), np.array([[1, 2], [1, 9]]))
assert np.allclose (get_unique_rows(np.zeros((10,10))), np.zeros(10))

**(0.75 балла) Задача 10.** Реализуйте функцию, которая во входной вещественной матрице ```X``` находит все значения ```nan``` и заменяет их на среднее арифметическое всех остальных элементов. Если все элементы матрицы ```nan```, то верните нулевую матрицу той же размерности.

In [46]:
a = np.array([[1, np.nan, 3],
             [np.nan, 5, 6],
             [7, 8, np.nan]])
b = np.array([np.nan, np.nan])


def replace_nans(X):
    return np.nan_to_num(X, nan=np.nanmean(X)) if not np.isnan(X).all() else np.zeros(X.shape)
print(replace_nans(a), replace_nans(b))
assert np.allclose (replace_nans(np.array([np.nan, np.nan])), np.zeros(2))
assert np.allclose (replace_nans(np.array([[2, np.nan], [np.nan, 3]])), np.array([[2., 2.5], [2.5, 3.]]))
# Level 10: просто встроенная функция

[[1. 5. 3.]
 [5. 5. 6.]
 [7. 8. 5.]] [0. 0.]


**(1 балл) Задача 11.** Напишите функцию, генерирующую [матрицу Вандермонда](https://ru.wikipedia.org/wiki/Определитель_Вандермонда), принимающую на вход вектор $(x_1, ... , x_n)$.

В этом задании **запрещается** пользоваться готовыми реализациями (например, [numpy.vander](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.vander.html)), а также [np.repeat](https://docs.scipy.org/doc/numpy/reference/generated/numpy.repeat.html) и [np.transpose](https://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html).

При решении задействуйте [np.reshape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html) и/или [np.newaxis](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.indexing.html).

In [41]:
def vander(x):
    v = np.empty((len(x), len(x)), dtype=np.promote_types(x.dtype, int))
    if len(x) > 0:
        v[:, 0] = 1
    if len(x) > 1:
        v[:, 1:] = x[:, None]
        np.multiply.accumulate(v[:, 1:], out=v[:, 1:], axis=1)
    return v
x = np.array([2, 4, 8])
vander(x)
assert np.allclose (np.vander(np.array([]), increasing=True), vander(np.array([])))
assert np.allclose (np.vander(np.array([1, 2, 3, 5]), increasing=True), vander(np.array([1, 2, 3, 5])))

# Level 11: Stackoverflow, что бы я без тебя делал...

**(1 балл) Задача 12.** Даны две вещественные матрицы ```X``` и ```Y``` с одинаковым числом столбцов и, в общем случае, различным числом строк. Необходимо реализовать функцию, вычисляющую матрицу попарных [косинусных коэффициентов](https://en.wikipedia.org/wiki/Cosine_similarity) между всеми $X_i$ и $Y_j$, где $X_i$ - $i$-ая строка матрицы $X$, а $Y_j$ - $j$-ая строка матрицы $Y$. 

В этом задании **запрещается** пользоваться готовыми реализациями, а также [np.repeat](https://docs.scipy.org/doc/numpy/reference/generated/numpy.repeat.html) и [np.transpose](https://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html).

При решении задействуйте [np.reshape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html) и/или [np.newaxis](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.indexing.html), [np.sqrt](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sqrt.html), [np.sum](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sum.html) и [np.power](https://docs.scipy.org/doc/numpy/reference/generated/numpy.power.html).

In [101]:
import numpy as np

def count_cosine_similarity(X, Y):
    return (X @ np.einsum('ji', Y)) / np.outer(np.linalg.norm(X, axis=1), np.linalg.norm(Y, axis=1))


count_cosine_similarity(np.array([[1, 2], [4, 8], [1, 2]]), np.array([[1, 2], [4, 2]]))


assert np.allclose(count_cosine_similarity(np.array([[1, 2], [4, 8], [1, 2]]), np.array([[1, 2], [4, 2]])), np.array([[1, 0.8], [1, 0.8], [1, 0.8]]))
assert np.allclose(count_cosine_similarity(np.ones((10, 5)), np.ones((3, 5))), np.ones((10, 3)))
#count_cosine_similarity(a1, a2)
#https://stackoverflow.com/questions/33160949/cosine-distance-between-two-matrices
#transpose запрещен, но про einsum никто ничего не говорил (про рекурсию, кстати, тоже, она может заменить циклы, это не было учтено)