# Задание по лекциям 1.

- Не нужно использовать эффективные вычислительные алгоритмы. Нужно использовать те алгоритмы, что были представлены на лекции или практических занятиях. 
- Остальное как обычно: за "похожие" решения всем задействованным 0 баллов; если используете решение из открытого источника — обязательно вставьте ссылку; не удаляйте формулировки; не выкладывайте в открытый источник.
- Можно использовать `numpy.array` для матриц и матричной арифметики и `numpy.linalg` для подсчёта ранга и определителя, для вычисления обратной матрицы, решения СЛУ и т.п. То есть то, что вы уже реализовывали в прошлом семестре, ещё раз реализовывать необязательно. Более того, можно использовать в любом из *заданий по лекциям* функции, реализованные ранее в других *заданиях по лекциям*. Если возникнут сомнения, можно ли использовать ту или иную функцию — лучше сразу поинтересуйтесь у меня.

In [1]:
import numpy as np

$\mathbb{R}^n$ — вещественнозначное пространство вектор-**столбцов**.

**(1 балл) Задание 1.** Реализовать функцию, принимающую на вход два набора 
$$
u = (u_1, \ldots, u_n),\ v = (v_1,\ldots,v_n)
$$
координат векторов (в стандартном базисе) из пространства $\mathbb{R}^n$, и выдающую 
- матрицу перехода от базиса $u$ к базису $v$, если оба этих набора являются базисами;
- None, иначе (альтернативный вариант — кидать исключение).

In [132]:
basis1 = np.random.randint(250, size = (3, 3))
basis2 = np.random.randint(250, size = (3, 3))

def transition_matrix(basis1, basis2):
    if np.abs(np.linalg.det(basis1) * np.linalg.det(basis2)) > 1e-6:
        return np.dot(np.linalg.inv(basis1.transpose()), basis2.transpose())
    raise(ValueError("det(A) or det(B) is zero!"))

print(basis1)
print(basis1)
transition_matrix(basis1, basis2)

[[ 29  85 120]
 [189 147 116]
 [105  71  33]]
[[ 29  85 120]
 [189 147 116]
 [105  71  33]]


array([[ -4.2397286 ,   5.41072878,  -0.7300418 ],
       [ 11.01685346,  -9.31501181,   4.97642212],
       [-16.94507785,  15.97739141,  -8.23211971]])

**(1 балл) Задание 2.** Реализовать функцию, принимающую на вход матрицу $A$ линейного оператора $\varphi: \mathbb{R}^n \to \mathbb{R}^n$ (в стандартном базисе) и набор координат $u = (u_1,\ldots,u_n)$ вектор-столбцов, и выдающую 
- матрицу оператора $\varphi$ в базисе $u$, если $u$ является базисом;
- None, иначе (альтернативный вариант — кидать исключение).

In [133]:
def linear_transition(linear_operator_matrix, matrix):
    if np.abs(np.linalg.det(matrix)) > 1e-6:
        return np.dot(np.dot(np.linalg.inv(matrix), linear_operator_matrix), matrix)
    raise(ValueError("Matrix determinant is zero!"))

linear_transition(basis1, basis2)

array([[-10.52079242,  97.69522076, 107.51655909],
       [215.20546929, 201.50632097, 308.46393497],
       [ 37.86779217,   9.9024109 ,  18.01447146]])

**(1.5 балла) Задание 3.** Реализовать функции, которые по данной матрице $A$ линейного оператора $\varphi: \mathbb{R}^n \to \mathbb{R}^n$ в стандартном базисе, выдадут:

- базис образа $\varphi$ (0.5 балла)
- базис ядра $\varphi$ (0.75 балла)
- размерности ядра и образа $\varphi$ (0.25 балла)

In [134]:
#Utility
def find_zero(row: np.array, start: int, end: int):
    for i in range(start, end):
        if np.abs(row[i]) > 2e-4:
            return i
    return -1

def gauss(matrix: np.array):
    t, row_len, rows = 0, len(matrix[0]), len(matrix)
    for i in range(min(rows, row_len)):
        zero = find_zero(matrix[0:, i], t, rows)
        if zero + 1: # check if row is not zero row
            if t - zero:
                matrix[[t, zero]] = matrix[[zero, t]]
            for j in range(rows):
                if j != t:
                    matrix[j] -= matrix[t] * (matrix[j][i] / matrix[t][i])
            t += 1

In [135]:
#1
def image_basis(matrix: np.array):
    lst = []
    gauss(matrix)
    len_matrix = len(matrix)
    for i in range(len_matrix):
        if any(matrix[i]):
            lst.append(matrix[i])
    return np.array(lst)

In [136]:
#2
def kernel_basis(matrix: np):
    lst, kkk = [], []
    gauss(matrix)
    len_matrix = len(matrix)
    for i in range(len_matrix):
        t = np.nonzero(matrix[0:, i])[0]
        if len(t) - 1:
            kkk.append(1)
            continue
        matrix[t[0]] /= matrix[t[0]][i]
        kkk.append(0)
    t = np.nonzero(kkk)[0]
    for i in range(np.sum(kkk)):
        lst.append([])
        for j in range(len_matrix):
            if not j in t:
                lst[i].append(-1 * matrix[j][t[i]])
            elif t[i] == j:
                lst[i].append(1)
            else:
                lst[i].append(0)
    return np.array(lst)

In [137]:
#3
def kernel_image_dims(matrix: np.array):
    k = len(image_basis(matrix))
    return len(matrix) - k, k

In [138]:
kernel_image_dims(np.array([[2, 0., 1, 5], [1, 2, 0, 3], [5, 2, 2, 13], [-3, -2, -1, -8]]))

(2, 2)