# Задание по лекциям 2.

- Не нужно использовать эффективные вычислительные алгоритмы. Нужно использовать те алгоритмы, что были представлены на лекции или практических занятиях. 
- Остальное как обычно: за "похожие" решения всем задействованным 0 баллов; если используете решение из открытого источника — обязательно вставьте ссылку; не удаляйте формулировки; не выкладывайте в открытый источник.
- Можно использовать `numpy.array` для матриц и матричной арифметики и `numpy.linalg` для подсчёта ранга и определителя, для вычисления обратной матрицы, решения СЛУ и т.п. То есть то, что вы уже реализовывали в прошлом семестре, ещё раз реализовывать необязательно. Более того, можно использовать в любом из *заданий по лекциям* функции, реализованные ранее в других *заданиях по лекциям*. Если возникнут сомнения, можно ли использовать ту или иную функцию — лучше сразу поинтересуйтесь у меня.

In [1]:
import numpy as np
from math import sqrt

$\mathbb{R}^n$ — вещественнозначное пространство вектор-**столбцов** со стандартным скалярным произведением.

**(1 балл) Задание 5.** Реализовать функцию, принимающую на вход набор координат $u = (u_1,\ldots,u_k),\ k\le n$ вектор-столбцов, и выдающую базис $$v = (v_1,\ldots,v_m),\ m \ge n-k,$$
ортогонального дополнения  для линейной оболочки данных векторов.

In [197]:
def find_zero(row: np.array, start: int, end: int):
    for i in range(start, end):
        if np.abs(row[i]) > 2e-4:
            return i
    return -1


def gauss(matrix: np.array):
    t, row_len, rows = 0, len(matrix[0]), len(matrix)
    for i in range(min(rows, row_len)):
        zero = find_zero(matrix[0:, i], t, rows)
        if zero + 1: # check if row is not zero row
            if t - zero:
                matrix[[t, zero]] = matrix[[zero, t]]
            for j in range(rows):
                if j != t:
                    matrix[j] -= matrix[t] * (matrix[j][i] / matrix[t][i])
            t += 1


def orthogonal_addition_basis(matrix: np.array):
    matrix, lst, kkk, len_matrix = matrix.copy(), [], [], len(matrix)
    gauss(matrix)
    for i in range(len_matrix):
        t = np.nonzero(matrix[0:, i])[0]
        if len(t) - 1:
            kkk.append(1)
            continue
        matrix[t[0]] /= matrix[t[0]][i]
        kkk.append(0)
        
    t = np.nonzero(kkk)[0]
    for i in range(np.sum(kkk)):
        lst.append([])
        for j in range(len(matrix)):
            if not j in t:
                lst[i].append(-1 * matrix[j][t[i]])
            elif t[i] == j:
                lst[i].append(1)
            else:
                lst[i].append(0)
    return np.array(lst)

orthogonal_addition_basis(np.array([[2, 0, 2, 0], [4, 0, 3, 0], [0, 0, 1, 0.], [3, 0, 0, 0]]))

array([[-0.,  1., -0.,  0.],
       [-0.,  0., -0.,  1.]])

**(1 балл) Задание 6.** Реализовать функцию, принимающую на вход набор координат $u = (u_1,\ldots,u_k),\ k\le n$ вектор-столбцов, и выдающую ортонормированный базис $$v = (v_1,\ldots,v_m),\ m \ge n-k,$$
для линейной оболочки данных векторов.

In [115]:
def orthonorm_basis(matrix: np.array):
    matrix = matrix.copy()
    gauss(matrix)
    matrix = matrix[:np.linalg.matrix_rank(matrix)]
    len_matrix = len(matrix)
    for i in range(len_matrix):
        for j in range(i):
            matrix[i] -= (np.dot(matrix[i], matrix[j] / np.dot(matrix[j], matrix[j]))) * matrix[j]
        matrix[i] /= np.sqrt(np.sum(matrix[i]*matrix[i]))
    return matrix

orthonorm_basis(np.array([[1, 2, 3, 4], [6, 4, 7, 5], [1, 0, 0, 8.], [5, 2, 4, 1]]))

array([[ 0.12403473,  0.        ,  0.        ,  0.99227788],
       [ 0.97986914, -0.15765221,  0.        , -0.12248364],
       [-0.08835308, -0.5577288 , -0.82523351,  0.01104413]])

**(1 балл) Задание 7.** Реализовать функцию, принимающую на вход набор координат $u = (u_1,\ldots,u_k),\ k\le n$ линейно независимых вектор-столбцов, и выдающую ортонормированный базис $$v = (v_1,\ldots,v_n)$$
всего пространства, такой что линейная оболочка векторов $(v_1,\ldots,v_k)$ совпадает с линейной оболочкой векторов $(u_1,\ldots,u_k)$.

In [196]:
def orthonorm_basis_task7(matrix: np.array):
    t = list(orthonorm_basis(matrix))
    t.append(orthonorm_basis(orthogonal_addition_basis(matrix))[0])
    return np.array(t)
    
orthonorm_basis_task7(np.array([[1, 0, 0, 2.], [1, 2, 3, 4], [5, 2, 4, 1], [6, 4, 7, 5]]))

array([[ 0.4472136 ,  0.        ,  0.        ,  0.89442719],
       [-0.88721395,  0.12674485,  0.        ,  0.44360698],
       [ 0.05997918,  0.5248178 ,  0.84856903, -0.02998959],
       [-0.09619721, -0.84172562,  0.52908468,  0.04809861]])